name: sportify
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: 
  cloud_firestore: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

 
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Sathoshi-Black.ttf
          weight: 900
        - asset: asset/fonts/Sathoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Sathoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Sathoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Sathoshi-Regular.ttf
          weight: 300